export default {
  id: "ollama",
  priority: 30,
  hasFree: true,
  alias: "ollama",
  display: {
    name: "Ollama Cloud",
    icon: "cloud",
    color: "#ffffffff",
    textIcon: "OL",
    website: "https://ollama.com",
    notice: {
      text: "Free tier: light usage, 1 cloud model at a time (limits reset every 5h & 7d). Pro $20/mo · Max $100/mo.",
      apiKeyUrl: "https://ollama.com/settings/keys",
    },
  },
  category: "freeTier",
  authType: "apikey",
  authModes: ["apikey"],
  transport: {
    baseUrl: "https://ollama.com/api/chat",
    validateUrl: "https://ollama.com/api/tags",
    format: "ollama",
  },
  models: [
    { id: "gpt-oss:120b", name: "GPT OSS 120B" },
    { id: "gpt-oss:20b", name: "GPT OSS 20B" },
    { id: "deepseek-v4-flash:preview", name: "DeepSeek V4 Flash Preview" },
    { id: "deepseek-v4-flash:0731", name: "DeepSeek V4 Flash 0731" },
    { id: "deepseek-v4-pro:preview", name: "DeepSeek V4 Pro Preview" },
    { id: "deepseek-v4-pro:0813", name: "DeepSeek V4 Pro 0813" },
    { id: "nemotron-3-nano:30b", name: "Nemotron 3 Nano 30B" },
    { id: "nemotron-3-super", name: "Nemotron 3 Super" },
    { id: "nemotron-3-ultra", name: "Nemotron 3 Ultra" },
    { id: "minimax-m2.7", name: "MiniMax M2.7" },
    { id: "minimax-m3", name: "MiniMax M3" },
    { id: "glm-5.1", name: "GLM 5.1" },
    { id: "glm-5.2", name: "GLM 5.2" },
    { id: "kimi-k2.6", name: "Kimi K2.6" },
    { id: "kimi-k2.7-code", name: "Kimi K2.7 Code" },
    { id: "kimi-k3", name: "Kimi K3" },
    { id: "qwen3.5:397b", name: "Qwen3.5 397B" },
    { id: "mistral-large-3:675b", name: "Mistral Large 3 675B" },
    { id: "gemma4:31b", name: "Gemma 4 31B" },
  ],
  serviceKinds: ["llm"],
  features: {
    usage: true,
    usageApikey: true,
  },
};
